logging:
  level:
    root: warn
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    default: dev
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
sentry:
  dsn: https://b7d01be9c8cea3219ad4dcb4fedee4f1@o4506897352884224.ingest.us.sentry.io/4506897387683840
  in-app-includes: hexlet.code.app
  traces-sample-rate: 1.0
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem